// installSnippetRuntime — the boot-time wiring point for the snippet
// runtime, the disk library resolver, and the seed `/lib/__seed__/`
// shims.
//
// Idempotent: subsequent calls update the in-process LibraryResolver
// singleton with a fresh DiskLibraryResolver bound to the supplied
// baseDir, and re-mirror the seed shim files.
//
// Seed shim format
// ----------------
// Each seed file under `<repo>/eval/seeds/generic/lib` or an explicitly enabled
// domain pack at `<repo>/eval/seeds/domains/<name>/lib` is a canonical authored
// seed (uses `fn({...})` against the repo SDK). `installSnippetRuntime`
// writes a thin re-export shim under `<baseDir>/lib/__seed__/<name>.ts`.
// The DiskLibraryResolver follows that re-export to the canonical file at
// import time. This keeps the resolver contract clean
// (`<baseDir>/lib/__seed__/<name>.ts` is the layered-lookup target) without
// exposing demo/domain-specific helpers to every mounted dataset.

import { promises as fsp } from "node:fs";
import path from "node:path";

import { setLibraryResolver } from "../sdk/index.js";

import { defaultBaseDir, locateRepoSubdir } from "../paths.js";
import { HookRegistry, setHookRegistry } from "../hooks/registry.js";
import { hooksEnabled } from "../hooks/mode.js";
import { DiskLibraryResolver } from "./library.js";
import { DiskSnippetRuntime } from "./runtime.js";

// --- Public surface ---------------------------------------------------------

export type InstallSnippetRuntimeOpts = {
  baseDir?: string;
  // Skip the seed shim mirror step. Useful for tests that supply their
  // own LibraryResolver via setLibraryResolver() afterwards.
  skipSeedMirror?: boolean;
  // Optional domain seed packs to expose alongside generic seeds.
  // Example: ["finqa"] mirrors seeds/domains/finqa/lib.
  seedDomains?: string[];
};

export type InstallSnippetRuntimeResult = {
  baseDir: string;
  snippetRuntime: DiskSnippetRuntime;
  libraryResolver: DiskLibraryResolver;
};

export async function installSnippetRuntime(
  opts: InstallSnippetRuntimeOpts = {},
): Promise<InstallSnippetRuntimeResult> {
  const baseDir = opts.baseDir ?? defaultBaseDir();

  if (!opts.skipSeedMirror) {
    await mirrorSeedShims(baseDir, {
      domains: opts.seedDomains ?? seedDomainsFromEnv(),
    });
  }

  const libraryResolver = new DiskLibraryResolver({ baseDir });
  setLibraryResolver(libraryResolver);
  // The hook registry is the public-callability gate for df.lib.<name>.
  // We install one whenever the snippet runtime boots so the df.lib
  // proxy can consult it even when the interface mode is "legacy" (the
  // registry is consulted but bypassed in that case). Tests that want
  // to isolate the resolver can `setHookRegistry(null)` afterwards.
  if (hooksEnabled()) {
    const registry = new HookRegistry({ baseDir, resolver: libraryResolver });
    setHookRegistry(registry);
  } else {
    setHookRegistry(null);
  }
  const snippetRuntime = new DiskSnippetRuntime();

  return {
    baseDir,
    snippetRuntime,
    libraryResolver,
  };
}

// --- Seed shim mirror -------------------------------------------------------

async function mirrorSeedShims(
  baseDir: string,
  opts: { domains: string[] },
): Promise<void> {
  const seedDirs = await resolveSeedLibDirs(opts.domains);
  if (seedDirs.length === 0) return;

  const targetDir = path.join(baseDir, "lib", "__seed__");
  await fsp.mkdir(targetDir, { recursive: true });

  for (const seedDir of seedDirs) {
    let entries: import("node:fs").Dirent[];
    try {
      entries = await fsp.readdir(seedDir, { withFileTypes: true });
    } catch {
      continue;
    }

    for (const entry of entries) {
      if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
      const name = entry.name.slice(0, -3);
      const srcAbs = path.join(seedDir, entry.name);
      const dst = path.join(targetDir, entry.name);
      // Re-export shim. `<srcAbs>` is an absolute on-disk path; ESM
      // `import ... from` accepts both absolute file paths and `file://`
      // URLs under Node, but TypeScript's NodeNext resolver prefers the
      // file URL form. The DiskLibraryResolver imports this shim through
      // `pathToFileURL(<dst>).href`, which yields a `file://` parent URL
      // against which the absolute `file://` href resolves cleanly.
      const sourceFileUrl = `file://${srcAbs.replace(/\\/g, "/")}`;
      const shim =
        `// Auto-generated by installSnippetRuntime - do not edit.\n` +
        `// Re-exports the canonical seed at ${srcAbs}.\n` +
        `export { ${name} } from "${sourceFileUrl}";\n`;
      await fsp.writeFile(dst, shim, "utf8");
    }
  }
}

async function resolveSeedLibDirs(domains: string[]): Promise<string[]> {
  const dirs: string[] = [];
  const genericDir = await locateRepoSubdir(path.join("eval", "seeds", "generic", "lib"));
  if (genericDir) {
    dirs.push(genericDir);
  } else {
    // eslint-disable-next-line no-console
    console.warn(
      "[snippet/install] could not locate seeds/generic/lib/; df.lib.<seedName> will fall back to tenant-overlay only",
    );
  }

  for (const domain of domains) {
    const clean = normalizeSeedDomain(domain);
    if (clean === null) continue;
    const domainDir = await locateRepoSubdir(
      path.join("eval", "seeds", "domains", clean, "lib"),
    );
    if (domainDir) {
      dirs.push(domainDir);
    } else {
      // eslint-disable-next-line no-console
      console.warn(
        `[snippet/install] could not locate seeds/domains/${clean}/lib/; skipping domain seed pack`,
      );
    }
  }
  return dirs;
}

function seedDomainsFromEnv(): string[] {
  return (process.env["DATAFETCH_SEED_DOMAINS"] ?? "")
    .split(",")
    .map((part) => part.trim())
    .filter((part) => part.length > 0);
}

function normalizeSeedDomain(domain: string): string | null {
  const clean = domain.trim().toLowerCase();
  if (!/^[a-z0-9_-]+$/.test(clean)) return null;
  return clean;
}
