// Workspace institutional-memory generator.
//
// This is the dataset-level equivalent of `df.d.ts`: a compact,
// server-maintained orientation file that tells future agents what this
// mounted workspace is good at, where to inspect the generated surface,
// and how to separate exploratory planning from committed execution.
//
// The file is intentionally Markdown, not a new registry format. Agents
// already know to read AGENTS.md/CLAUDE.md in large codebases; we reuse
// that discovery prior and keep the actual executable contract in
// `df.d.ts` plus flat TypeScript files.

import { promises as fsp } from "node:fs";
import path from "node:path";

import type { MountDescriptor } from "../sdk/index.js";
import { readFrontmatterHead } from "../sdk/frontmatter.js";
import { DiskLibraryResolver } from "../snippet/library.js";
import { hooksEnabled } from "../hooks/mode.js";
import { listManifests } from "../hooks/manifest.js";
import type { VfsHookManifest } from "../hooks/types.js";

export type RegenerateWorkspaceMemoryOpts = {
  baseDir: string;
  tenantId?: string;
  mountIds?: string[];
};

type InventoryRecord = {
  mountId: string;
  substrate?: string;
  generatedAt?: string;
  collections?: Array<{
    ident: string;
    name: string;
    rows: number;
    fingerprint: string;
  }>;
};

type MountSummary = {
  mountId: string;
  substrate: string;
  collections: CollectionSummary[];
};

type CollectionSummary = {
  ident: string;
  name: string;
  rows: number;
  kind: string;
  fingerprint: string;
  requiredFields: string[];
  textFields: string[];
  labelFields: string[];
  numberFields: string[];
  variantCount: number;
  intentHint: string;
};

type LibrarySummary = {
  name: string;
  intent: string;
  isTool: boolean;
};

const GENERATED_MARKER = "<!-- datafetch:generated workspace-memory -->";

// Write `<baseDir>/AGENTS.md` and, when safe, `<baseDir>/CLAUDE.md` as a
// symlink to it. Best-effort: a failure should not block connect,
// publish, or crystallisation paths.
export async function regenerateWorkspaceMemory(
  opts: RegenerateWorkspaceMemoryOpts,
): Promise<void> {
  try {
    await fsp.mkdir(opts.baseDir, { recursive: true });
    const text = await renderWorkspaceMemory(opts);
    await writeFileIfChanged(path.join(opts.baseDir, "AGENTS.md"), text);
    await ensureClaudeAlias(opts.baseDir, text);
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn(
      `[workspace-memory] regenerate failed: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }
}

export async function renderWorkspaceMemory(
  opts: RegenerateWorkspaceMemoryOpts,
): Promise<string> {
  const mounts = await discoverMounts(opts.baseDir, opts.mountIds);
  const library =
    opts.tenantId !== undefined
      ? await discoverLibrary(opts.baseDir, opts.tenantId)
      : [];

  const lines: string[] = [];
  lines.push(GENERATED_MARKER);
  lines.push("# Datafetch Workspace Memory");
  lines.push("");
  lines.push(
    "Auto-generated by the datafetch server. Do not edit by hand; refresh the mount or the learned TypeScript files instead.",
  );
  lines.push("");
  lines.push("## First Reads");
  lines.push("");
  lines.push("1. Read this file for the dataset-level mental model.");
  lines.push("2. Read `df.d.ts` for the exact executable TypeScript surface.");
  lines.push("3. Read `mounts/<mount-id>/README.md` for per-mount details.");
  lines.push(
    "4. Inspect `_descriptor.json`, `_samples.json`, and `_stats.json` before deciding that a field or category is absent.",
  );
  lines.push("");
  lines.push("## Code-Native Discovery");
  lines.push("");
  lines.push(
    "- Treat the workspace like a small codebase: use `ls`, `find`, `rg`, `cat`, TypeScript symbols, and LSP/IDE references when available.",
  );
  lines.push(
    "- `df.d.ts` is the source of truth for callable `df.db.*`, `df.tool.*`, `df.lib.*`, and `df.answer(...)` shapes.",
  );
  lines.push(
    "- `lib/` contains tenant-local TypeScript. Read a helper's source before relying on an output shape that is not obvious from its JSDoc.",
  );
  lines.push(
    "- `datafetch apropos '<intent words>'` and `datafetch man <name>` are filesystem-style discovery aids, not replacements for reading the typed code surface.",
  );
  lines.push(
    "- Prefer reusing a matching `df.lib.*` workflow; compose directly from `df.db.*` or `df.tool.*` when no helper fits.",
  );
  lines.push("");
  lines.push("## Namespace Boundaries");
  lines.push("");
  lines.push(
    "- `df.db.*` is the mounted system/provider data surface. Use it for cold reads, search, sampling, and fallback composition when no tenant helper fits.",
  );
  lines.push(
    "- `df.lib.*` is tenant-local TypeScript. It is the warm path for learned workflows, but only call helpers that are visible in `df.d.ts` and not quarantined by hook manifests.",
  );
  lines.push(
    "- `df.tool.*` is a governed adapter bridge for explicit external tool catalogs. Use it when the typed manifest exposes a tool and no better tenant helper exists.",
  );
  lines.push(
    "- `df.answer(...)` is the typed commit boundary. Return the final answer, evidence, derivation, and assumptions there rather than printing ad hoc output.",
  );
  lines.push("");
  lines.push("## Workspace Contract");
  lines.push("");
  lines.push(
    "- In an intent workspace, `datafetch run scripts/scratch.ts` is for sampling, broad search, scratch TypeScript, and validating what the dataset can answer.",
  );
  lines.push(
    "- `datafetch commit scripts/answer.ts` is the committed trajectory: one repeatable TypeScript workflow that returns `df.answer(...)` and can be learned from after validation.",
  );
  lines.push(
    "- Do not answer from `tmp/runs/N` output. Convert the validated plan into `scripts/answer.ts`, commit it, then answer from `result/answer.json`.",
  );
  lines.push(
    "- After commit, inspect `result/HEAD.json` and `result/report.md` first. `result/` is the accepted HEAD view; rejected attempts stay under `result/commits/N/`.",
  );
  lines.push(
    "- Use `result/source.ts`, `result/graph.txt`, and `result/tests/replay.txt` to review the committed TypeScript source, read/compute/tool/write graph, replay contract, assumptions, and learning eligibility.",
  );
  lines.push(
    "- `result/report.md` may show learning eligibility, but hook manifests remain the authority for final `df.lib.*` callability.",
  );
  lines.push(
    "- Observer learning decisions, including skipped and crystallised outcomes, are append-only under `observer/<tenant>/decisions.jsonl` in the datafetch home.",
  );
  lines.push(
    "- Make probabilistic steps explicit as reusable `df.lib.*` interfaces or `fn({ body: agent(...) })` functions with skill markdown sidecars.",
  );
  lines.push(
    "- For helper code needed only by the current answer, write `scripts/helpers.ts` and import it from `scripts/answer.ts`; do not create nested `lib/<tenant>/...` paths inside this workspace.",
  );
  lines.push(
    "- Treat `lib/` as the mounted tenant library root. New durable `df.lib.*` callability should come from validated observer promotion plus hook manifests, not from assuming a fresh file is immediately callable.",
  );
  lines.push(
    "- If a broad exploration produces a narrower useful sub-intent, keep that logic in `scripts/answer.ts` and mark the committed `df.answer(...)` with `intent: { name, description, parent, relation }`.",
  );
  lines.push(
    "- Use `relation: \"same\"` for the original mount intent, `\"derived\"` or `\"sibling\"` for useful sub-trajectories, and `\"drifted\"` or `\"unrelated\"` when the worktree purpose changed.",
  );
  lines.push("");
  lines.push("A validated plan should establish:");
  lines.push("");
  lines.push("- what the mounted dataset is expert on;");
  lines.push("- which concepts are explicit fields versus derived categories;");
  lines.push("- whether the sample is representative enough or needs a broader search;");
  lines.push("- how polymorphic rows, missing fields, units, or aliases will be handled;");
  lines.push("- the exact `df.db.*` and `df.lib.*` calls the committed answer file will run.");
  lines.push("");
  lines.push("## Mounted Dataset Surface");
  lines.push("");
  if (mounts.length === 0) {
    lines.push("- No mounted datasets found on disk yet.");
  } else {
    for (const mount of mounts) {
      lines.push(`### ${mount.mountId}`);
      lines.push("");
      lines.push(`Substrate: \`${mount.substrate}\`.`);
      lines.push(
        `Read \`mounts/${mount.mountId}/README.md\` before issuing task-specific queries.`,
      );
      lines.push("");
      if (mount.collections.length === 0) {
        lines.push("- No collections listed in `_inventory.json`.");
        lines.push("");
        continue;
      }
      for (const coll of mount.collections) {
        lines.push(
          `- \`df.db.${coll.ident}\` -> \`${coll.name}\`: ${formatRows(
            coll.rows,
          )} rows, ${coll.kind}. ${coll.intentHint}`,
        );
        if (coll.requiredFields.length > 0) {
          lines.push(
            `  Required: ${coll.requiredFields.map(code).join(", ")}.`,
          );
        }
        if (coll.textFields.length > 0) {
          lines.push(`  Text/search: ${coll.textFields.map(code).join(", ")}.`);
        }
        if (coll.labelFields.length > 0) {
          lines.push(`  Labels: ${coll.labelFields.map(code).join(", ")}.`);
        }
        if (coll.numberFields.length > 0) {
          lines.push(`  Numeric: ${coll.numberFields.map(code).join(", ")}.`);
        }
        if (coll.variantCount > 0) {
          lines.push(`  Polymorphic variants observed: ${coll.variantCount}.`);
        }
      }
      lines.push("");
    }
  }

  lines.push("## Learned Interface And Seeded TypeScript Surface");
  lines.push("");
  if (opts.tenantId === undefined) {
    lines.push("- Tenant-specific library listing appears after session connect.");
  } else if (library.length === 0) {
    lines.push(
      `- No loadable \`df.lib.*\` functions found for tenant \`${opts.tenantId}\` yet.`,
    );
  } else {
    const tools = library.filter((entry) => entry.isTool);
    const primitives = library.filter((entry) => !entry.isTool);
    if (tools.length > 0) {
      lines.push("### Learned Interfaces");
      lines.push("");
      for (const entry of tools.slice(0, 12)) {
        lines.push(`- \`df.lib.${entry.name}\`: ${entry.intent}`);
      }
      if (tools.length > 12) {
        lines.push(`- ... ${tools.length - 12} more learned interfaces in \`df.d.ts\`.`);
      }
      lines.push("");
    }
    if (primitives.length > 0) {
      lines.push("### Primitives");
      lines.push("");
      for (const entry of primitives.slice(0, 12)) {
        lines.push(`- \`df.lib.${entry.name}\`: ${entry.intent}`);
      }
      if (primitives.length > 12) {
        lines.push(
          `- ... ${primitives.length - 12} more primitives in \`df.d.ts\`.`,
        );
      }
      lines.push("");
    }
  }

  lines.push("## Committed Answer File Shape");
  lines.push("");
  lines.push("Use flat TypeScript snippet code. Keep the full answer path in the file:");
  lines.push("");
  lines.push("```ts");
  lines.push("const candidates = await df.db.<ident>.search(\"<query>\", { limit: 50 });");
  lines.push("const picked = await df.lib.<selector>({ question: \"<question>\", candidates });");
  lines.push("const plan = await df.lib.<planner>({ question: \"<question>\", filing: picked.value });");
  lines.push("const out = await df.lib.<executor>({ filing: picked.value, plan: plan.value });");
  lines.push("");
  lines.push("return df.answer({");
  lines.push("  intent: {");
  lines.push("    name: \"<short-stable-name>\",");
  lines.push("    parent: \"<original intent>\",");
  lines.push("    relation: \"same\",");
  lines.push("    description: \"<what this committed trajectory answers>\",");
  lines.push("  },");
  lines.push("  status: \"answered\",");
  lines.push("  value: out.value,");
  lines.push("  evidence: [{ ref: picked.value.id ?? picked.value.filename }],");
  lines.push("  derivation: { operation: \"derived-from-visible-df-calls\" },");
  lines.push("});");
  lines.push("```");
  lines.push("");
  lines.push(
    "If no existing selector/planner/executor fits, keep the missing immediate helper in `scripts/helpers.ts`, import it from `scripts/answer.ts`, and commit the visible trajectory. Validated observer promotion can later turn that repeated workflow into a callable tenant `df.lib.*` helper under the mounted `lib/` surface.",
  );
  lines.push("");

  return `${lines.join("\n").trimEnd()}\n`;
}

async function discoverMounts(
  baseDir: string,
  mountIds: string[] | undefined,
): Promise<MountSummary[]> {
  const mountsRoot = path.join(baseDir, "mounts");
  const ids = mountIds ?? (await listDirs(mountsRoot));
  const out: MountSummary[] = [];
  for (const mountId of ids.sort()) {
    const inventory = await readInventory(path.join(mountsRoot, mountId));
    if (!inventory) continue;
    const collections: CollectionSummary[] = [];
    for (const c of inventory.collections ?? []) {
      const descriptor = await readDescriptor(
        path.join(mountsRoot, mountId, c.name, "_descriptor.json"),
      );
      collections.push(summarizeCollection(c, descriptor));
    }
    out.push({
      mountId: inventory.mountId || mountId,
      substrate: inventory.substrate ?? "unknown",
      collections,
    });
  }
  return out;
}

async function discoverLibrary(
  baseDir: string,
  tenantId: string,
): Promise<LibrarySummary[]> {
  const resolver = new DiskLibraryResolver({ baseDir });
  let entries: Awaited<ReturnType<DiskLibraryResolver["list"]>>;
  try {
    entries = await resolver.list(tenantId);
  } catch {
    return [];
  }
  let callableNames: Set<string> | null = null;
  if (hooksEnabled()) {
    const manifests = await listManifests(baseDir, tenantId);
    callableNames = new Set(
      manifests
        .filter((m: VfsHookManifest) =>
          m.callability === "callable" || m.callability === "callable-with-fallback",
        )
        .map((m: VfsHookManifest) => m.name),
    );
  }
  const summaries = await Promise.all(
    entries.map(async (entry) => {
      const source = await resolveLibrarySourcePath(baseDir, tenantId, entry.name);
      if (callableNames !== null && !source.isSeed && !callableNames.has(entry.name)) {
        return null;
      }
      const head = await readFrontmatterHead(source.path);
      const intent = compact(
        head.description ??
          entry.spec.intent ??
          "typed datafetch callable; inspect df.d.ts or source before use",
        180,
      );
      return {
        name: entry.name,
        intent,
        isTool: head.isTool,
      };
    }),
  );
  const visibleSummaries = summaries.filter((s): s is LibrarySummary => s !== null);
  visibleSummaries.sort((a, b) => {
    if (a.isTool !== b.isTool) return a.isTool ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
  return visibleSummaries;
}

async function resolveLibrarySourcePath(
  baseDir: string,
  tenantId: string,
  name: string,
): Promise<{ path: string; isSeed: boolean }> {
  const tenantPath = path.join(baseDir, "lib", tenantId, `${name}.ts`);
  if (await fileExists(tenantPath)) return { path: tenantPath, isSeed: false };
  const seedPath = path.join(baseDir, "lib", "__seed__", `${name}.ts`);
  if (await fileExists(seedPath)) return { path: seedPath, isSeed: true };
  return { path: tenantPath, isSeed: false };
}

async function fileExists(file: string): Promise<boolean> {
  try {
    const stat = await fsp.stat(file);
    return stat.isFile();
  } catch {
    return false;
  }
}

async function listDirs(root: string): Promise<string[]> {
  try {
    const entries = await fsp.readdir(root, { withFileTypes: true });
    return entries.filter((e) => e.isDirectory()).map((e) => e.name);
  } catch {
    return [];
  }
}

async function readInventory(mountRoot: string): Promise<InventoryRecord | null> {
  try {
    return JSON.parse(
      await fsp.readFile(path.join(mountRoot, "_inventory.json"), "utf8"),
    ) as InventoryRecord;
  } catch {
    return null;
  }
}

async function readDescriptor(file: string): Promise<MountDescriptor | null> {
  try {
    return JSON.parse(await fsp.readFile(file, "utf8")) as MountDescriptor;
  } catch {
    return null;
  }
}

function summarizeCollection(
  collection: NonNullable<InventoryRecord["collections"]>[number],
  descriptor: MountDescriptor | null,
): CollectionSummary {
  const fields = descriptor?.fields ?? {};
  const requiredFields: string[] = [];
  const textFields: string[] = [];
  const labelFields: string[] = [];
  const numberFields: string[] = [];
  for (const [name, field] of Object.entries(fields)) {
    if (field.presence >= 0.95) requiredFields.push(name);
    if (field.role === "text" || field.embeddable) textFields.push(name);
    if (field.role === "label") labelFields.push(name);
    if (field.role === "number") numberFields.push(name);
  }
  return {
    ident: collection.ident,
    name: collection.name,
    rows: collection.rows,
    kind: descriptor?.kind ?? "unknown shape",
    fingerprint: collection.fingerprint,
    requiredFields: requiredFields.slice(0, 8),
    textFields: textFields.slice(0, 8),
    labelFields: labelFields.slice(0, 8),
    numberFields: numberFields.slice(0, 8),
    variantCount: descriptor?.polymorphic_variants?.length ?? 0,
    intentHint: inferIntentHint(collection.name, fields),
  };
}

function inferIntentHint(
  collectionName: string,
  fields: MountDescriptor["fields"],
): string {
  const names = new Set(
    [collectionName, ...Object.keys(fields)].map((s) => s.toLowerCase()),
  );
  if (
    hasAny(names, ["question", "answer", "program", "table", "filing", "ticker"])
  ) {
    return "Looks suited to financial question answering over filing/table records.";
  }
  if (hasAny(names, ["body", "content", "text", "title", "summary"])) {
    return "Looks suited to document retrieval and text extraction workflows.";
  }
  if (hasAny(names, ["timestamp", "date", "created_at", "time"])) {
    return "Looks suited to time-filtered retrieval or trend analysis.";
  }
  return "Start with descriptor and samples to learn the dataset's expertise.";
}

function hasAny(values: Set<string>, needles: string[]): boolean {
  for (const needle of needles) {
    if (values.has(needle)) return true;
  }
  return false;
}

async function writeFileIfChanged(file: string, text: string): Promise<void> {
  let existing: string | null = null;
  try {
    existing = await fsp.readFile(file, "utf8");
  } catch {
    // missing
  }
  if (existing === text) return;
  await fsp.mkdir(path.dirname(file), { recursive: true });
  await fsp.writeFile(file, text, "utf8");
}

async function ensureClaudeAlias(baseDir: string, text: string): Promise<void> {
  const alias = path.join(baseDir, "CLAUDE.md");
  try {
    const st = await fsp.lstat(alias);
    if (st.isSymbolicLink()) {
      const target = await fsp.readlink(alias);
      if (target === "AGENTS.md") return;
      await fsp.unlink(alias);
      await createClaudeSymlink(alias, text);
      return;
    }
    const existing = await fsp.readFile(alias, "utf8");
    if (existing.startsWith(GENERATED_MARKER)) {
      await fsp.unlink(alias);
      await createClaudeSymlink(alias, text);
    }
    return;
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    if (code !== "ENOENT") throw err;
  }
  await createClaudeSymlink(alias, text);
}

async function createClaudeSymlink(alias: string, text: string): Promise<void> {
  try {
    await fsp.symlink("AGENTS.md", alias);
  } catch {
    await writeFileIfChanged(alias, text);
  }
}

function code(s: string): string {
  return `\`${s}\``;
}

function formatRows(rows: number): string {
  return new Intl.NumberFormat("en-US").format(rows);
}

function compact(s: string, max: number): string {
  const oneLine = s.replace(/\s+/g, " ").trim();
  if (oneLine.length <= max) return oneLine;
  return `${oneLine.slice(0, max - 1).trimEnd()}...`;
}
